#!/bin/sh
# /etc/init.d/SCLoRaGWd

### BEGIN INIT INFO
# Provides:          SCLoRaGWd
# Required-Start:    $all
# Required-Stop:     $all
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Start-Before:
# X-Start-After:     openhab
# Short-Description: Single Channel LoRa Packet Forwarder daemon
# Description:       Get data from LoRa module and push it to TheThingsNetwork
### END INIT INFO

# Adapted from noip2 (http://www.togaware.com/linux/survivor/No_IP_Manual.html)

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions
DAEMON=/usr/local/bin/SCLoRaGWd
NAME=SCLoRaGWd
PIDFILE=/var/run/SCLoRaGWd.pid

test -x $DAEMON || exit 0

case "$1" in
    start)
        echo -n "Starting LoRa Gateway: "
        start-stop-daemon --start --exec $DAEMON --pidfile $PIDFILE --name $NAME
        echo $NAME
        ;;
    stop)
        echo -n "Stopping Lora Gateway daemon: "
        start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON --name $NAME
        echo $NAME
        ;;

    restart)
        echo -n "Restarting Lora Gateway daemon: "
        start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
        start-stop-daemon --start --exec $DAEMON
        echo $NAME
        ;;
    *)
        echo "Usage: $0 start|stop|restart"
        exit 1
        ;;
esac

exit 0